//! Support for the broker-backed integration tests.
//!
//! These tests speak to a **real Mosquitto**, not a mock. Testing against a
//! mock MQTT client would be testing a model of MQTT, and the properties that
//! matter here — retention, the will, ACL isolation, redelivery — are broker
//! behaviour, not client behaviour (PRD 020 §Problem).
//!
//! # Configuration
//!
//! Credentials come from the repository's `.env`, which is gitignored and
//! generated by the documented local setup:
//!
//! ```bash
//! cp .env.example .env
//! ./scripts/gen-mosquitto-passwd.sh
//! docker compose -f deploy/docker-compose.yml up -d mosquitto
//! ```
//!
//! # Skipping
//!
//! On a machine with no broker the tests print a loud skip and pass, so a fresh
//! clone is green. Set `RHIZO_REQUIRE_BROKER=1` — as CI does — to turn every
//! skip into a failure, because a suite that can silently skip its own subject
//! is a suite that eventually proves nothing.

#![allow(dead_code, clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

use device_simulator::clock::AcceleratedClock;
use rumqttc::{AsyncClient, Event, MqttOptions, Packet, QoS};
use tokio::sync::mpsc;

/// How long a test waits for a message that should already be in flight.
pub const RECEIVE_TIMEOUT: Duration = Duration::from_secs(10);
/// The harness's tick, matching `runner::TICK_INTERVAL`.
const TICK: Duration = Duration::from_millis(100);

/// Broker coordinates and the accounts the tests use.
#[derive(Clone, Debug)]
pub struct TestBroker {
    /// `mqtt://host:port`.
    pub url: String,
    /// Host, split out for building clients directly.
    pub host: String,
    /// Port.
    pub port: u16,
    /// The fleet-wide edge account.
    pub edge_username: String,
    /// Its password.
    pub edge_password: String,
    /// Per-device passwords, keyed by `device_id`.
    pub device_passwords: HashMap<String, String>,
}

impl TestBroker {
    /// The password for a device account.
    pub fn device_password(&self, device_id: &str) -> String {
        self.device_passwords
            .get(device_id)
            .unwrap_or_else(|| panic!("no password for {device_id} in .env"))
            .clone()
    }

    /// Connects a subscriber using the edge account.
    pub async fn edge_subscriber(&self, client_id: &str, filter: &str) -> Subscriber {
        Subscriber::connect(
            self,
            client_id,
            &self.edge_username,
            &self.edge_password,
            filter,
        )
        .await
    }
}

/// Serialises broker-backed tests within this binary.
///
/// Every test drives the same `plant-node-01` account and the same retained
/// topics, because the broker's ACL grants a device only its own subtree and the
/// available accounts come from `.env`. Running two such tests at once would
/// have them evict each other's connection and overwrite each other's retained
/// status — a flake whose cause is invisible in the failure message.
static BROKER_LOCK: std::sync::OnceLock<std::sync::Arc<tokio::sync::Mutex<()>>> =
    std::sync::OnceLock::new();

/// Exclusive access to the broker for the duration of one test.
pub struct BrokerGuard {
    broker: TestBroker,
    _guard: tokio::sync::OwnedMutexGuard<()>,
}

impl std::ops::Deref for BrokerGuard {
    type Target = TestBroker;

    fn deref(&self) -> &Self::Target {
        &self.broker
    }
}

/// Resolves the broker configuration, or explains why the test is skipped.
///
/// Returns `None` when the broker cannot be reached or `.env` has no
/// credentials, unless `RHIZO_REQUIRE_BROKER` is set. The returned guard holds
/// exclusive access until it is dropped.
pub async fn broker(test_name: &str) -> Option<BrokerGuard> {
    let broker = resolve(test_name).await?;
    let guard = std::sync::Arc::clone(
        BROKER_LOCK.get_or_init(|| std::sync::Arc::new(tokio::sync::Mutex::new(()))),
    )
    .lock_owned()
    .await;
    Some(BrokerGuard {
        broker,
        _guard: guard,
    })
}

async fn resolve(test_name: &str) -> Option<TestBroker> {
    let required = std::env::var("RHIZO_REQUIRE_BROKER").is_ok_and(|v| !v.is_empty());
    let broker = match load_broker() {
        Ok(b) => b,
        Err(reason) => return skip(test_name, &reason, required),
    };
    if tokio::time::timeout(
        Duration::from_secs(2),
        tokio::net::TcpStream::connect((broker.host.as_str(), broker.port)),
    )
    .await
    .is_err_and(|_| true)
        || tokio::net::TcpStream::connect((broker.host.as_str(), broker.port))
            .await
            .is_err()
    {
        return skip(
            test_name,
            &format!("no broker listening on {}:{}", broker.host, broker.port),
            required,
        );
    }
    Some(broker)
}

fn skip(test_name: &str, reason: &str, required: bool) -> Option<TestBroker> {
    assert!(
        !required,
        "RHIZO_REQUIRE_BROKER is set but {test_name} cannot run: {reason}"
    );
    eprintln!(
        "SKIPPING {test_name}: {reason}.\n  \
         Start it with: docker compose -f deploy/docker-compose.yml up -d mosquitto\n  \
         Set RHIZO_REQUIRE_BROKER=1 to make this a failure instead."
    );
    None
}

fn load_broker() -> Result<TestBroker, String> {
    let root = workspace_root();
    let env_path = root.join(".env");
    let contents = std::fs::read_to_string(&env_path)
        .map_err(|e| format!("could not read {}: {e}", env_path.display()))?;
    let mut values = HashMap::new();
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            values.insert(
                key.trim().to_owned(),
                value.trim().trim_matches('"').to_owned(),
            );
        }
    }
    let url = std::env::var("RHIZO_TEST_BROKER").unwrap_or_else(|_| "mqtt://127.0.0.1:1883".into());
    let (host, port) = {
        let (host, port) = url
            .strip_prefix("mqtt://")
            .and_then(|a| a.rsplit_once(':'))
            .ok_or_else(|| format!("`{url}` is not mqtt://host:port"))?;
        let port: u16 = port.parse().map_err(|_| format!("bad port in `{url}`"))?;
        (host.to_owned(), port)
    };

    let edge_username = values
        .get("MQTT_USERNAME")
        .cloned()
        .ok_or("MQTT_USERNAME is not set in .env")?;
    let edge_password = values
        .get("MQTT_PASSWORD")
        .cloned()
        .ok_or("MQTT_PASSWORD is not set in .env")?;

    let mut device_passwords = HashMap::new();
    for device_id in values
        .get("DEVICE_IDS")
        .map(|s| s.split(',').map(str::trim).map(str::to_owned).collect())
        .unwrap_or_else(Vec::new)
    {
        // The variable name is documented in .env.example.
        let key = format!(
            "RHIZO_DEVICE_{}_PASSWORD",
            device_id.to_uppercase().replace('-', "_")
        );
        if let Some(password) = values.get(&key) {
            device_passwords.insert(device_id, password.clone());
        }
    }
    if device_passwords.is_empty() {
        return Err("no RHIZO_DEVICE_*_PASSWORD entries in .env".into());
    }

    Ok(TestBroker {
        url,
        host: host.to_owned(),
        port,
        edge_username,
        edge_password,
        device_passwords,
    })
}

/// The repository root, found from this file's compile-time path.
pub fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crates/<name> is two levels below the workspace root")
        .to_path_buf()
}

/// A message as it arrived from the broker.
#[derive(Clone, Debug)]
pub struct Received {
    /// Topic.
    pub topic: String,
    /// Raw payload.
    pub payload: Vec<u8>,
    /// Whether the broker marked it retained.
    ///
    /// **The assertion that matters.** A message delivered to a *fresh*
    /// subscriber with this flag set is stored broker-side; the same message
    /// arriving live has it clear.
    pub retain: bool,
}

impl Received {
    /// Decodes the payload as JSON.
    pub fn json(&self) -> serde_json::Value {
        serde_json::from_slice(&self.payload).expect("payload must be JSON")
    }
}

/// A subscriber that collects everything delivered to it.
pub struct Subscriber {
    client: AsyncClient,
    rx: mpsc::UnboundedReceiver<Received>,
    task: tokio::task::JoinHandle<()>,
}

impl Subscriber {
    /// Connects, subscribes, and starts collecting.
    ///
    /// Returns only once the subscription is acknowledged, so a test that
    /// publishes immediately afterwards cannot race the SUBACK.
    pub async fn connect(
        broker: &TestBroker,
        client_id: &str,
        username: &str,
        password: &str,
        filter: &str,
    ) -> Self {
        let mut options = MqttOptions::new(client_id, broker.host.clone(), broker.port);
        options.set_credentials(username, password);
        options.set_keep_alive(Duration::from_secs(5));
        options.set_clean_session(true);
        let (client, mut eventloop) = AsyncClient::new(options, 64);
        let (tx, rx) = mpsc::unbounded_channel();
        let (ready_tx, ready_rx) = tokio::sync::oneshot::channel();
        let filter = filter.to_owned();
        let subscribe_client = client.clone();
        let task = tokio::spawn(async move {
            let mut ready = Some(ready_tx);
            loop {
                match eventloop.poll().await {
                    Ok(Event::Incoming(Packet::ConnAck(_))) => {
                        let _ = subscribe_client.subscribe(&filter, QoS::AtLeastOnce).await;
                    }
                    Ok(Event::Incoming(Packet::SubAck(_))) => {
                        if let Some(ready) = ready.take() {
                            let _ = ready.send(());
                        }
                    }
                    Ok(Event::Incoming(Packet::Publish(p))) => {
                        if tx
                            .send(Received {
                                topic: p.topic,
                                payload: p.payload.to_vec(),
                                retain: p.retain,
                            })
                            .is_err()
                        {
                            return;
                        }
                    }
                    Ok(_) => {}
                    Err(_) => tokio::time::sleep(Duration::from_millis(100)).await,
                }
            }
        });
        tokio::time::timeout(RECEIVE_TIMEOUT, ready_rx)
            .await
            .expect("subscriber did not connect in time")
            .expect("subscriber task ended before subscribing");
        Self { client, rx, task }
    }

    /// A publishing handle on the same connection.
    pub fn client(&self) -> AsyncClient {
        self.client.clone()
    }

    /// Waits for the next message matching a predicate, ignoring others.
    pub async fn next_matching(
        &mut self,
        timeout: Duration,
        mut matches: impl FnMut(&Received) -> bool,
    ) -> Option<Received> {
        let deadline = tokio::time::Instant::now() + timeout;
        loop {
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() {
                return None;
            }
            match tokio::time::timeout(remaining, self.rx.recv()).await {
                Ok(Some(received)) if matches(&received) => return Some(received),
                Ok(Some(_)) => {}
                Ok(None) | Err(_) => return None,
            }
        }
    }

    /// Collects everything delivered within a window.
    pub async fn drain_for(&mut self, window: Duration) -> Vec<Received> {
        let deadline = tokio::time::Instant::now() + window;
        let mut all = Vec::new();
        loop {
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() {
                return all;
            }
            match tokio::time::timeout(remaining, self.rx.recv()).await {
                Ok(Some(received)) => all.push(received),
                Ok(None) | Err(_) => return all,
            }
        }
    }
}

impl Drop for Subscriber {
    fn drop(&mut self) {
        self.task.abort();
    }
}

/// A simulator running in the test process, driven by the real driver against
/// the real broker.
///
/// In-process rather than a subprocess because the properties under test are
/// protocol-level, and dropping the connection closes its socket exactly as a
/// killed process does — which is what makes the will fire.
pub struct SimulatedDevice {
    device: std::sync::Arc<std::sync::Mutex<device_simulator::Device>>,
    steps: mpsc::UnboundedReceiver<device_simulator::mqtt::Step>,
    kill: std::sync::Arc<std::sync::atomic::AtomicBool>,
    thread: Option<std::thread::JoinHandle<()>>,
    shutdown: Option<tokio::sync::oneshot::Sender<()>>,
    finished: Option<tokio::sync::oneshot::Receiver<()>>,
}

impl SimulatedDevice {
    /// Starts a device with the given extra command-line flags and waits until
    /// it is connected.
    pub async fn start(broker: &TestBroker, device_id: &str, extra: &[&str]) -> Self {
        use clap::Parser;
        let password = broker.device_password(device_id);
        // A scratch state file unless the caller named one. Without this every
        // broker test would share `plant-node-01.state.json` in the working
        // directory, and one test's spent daily budget would silently refuse
        // the next test's dose — a failure whose cause is nowhere in the
        // assertion that reports it.
        let state_file = scratch_state_file();
        let state_file = state_file.display().to_string();
        let mut args = vec![
            "device-simulator",
            "--device-id",
            device_id,
            "--broker",
            &broker.url,
            "--password",
            &password,
        ];
        if !extra.iter().any(|a| a.starts_with("--state-file")) {
            args.push("--state-file");
            args.push(&state_file);
        }
        args.extend_from_slice(extra);
        let cli = device_simulator::Cli::try_parse_from(args).expect("test flags must parse");
        cli.validate().expect("test flags must validate");

        let device =
            std::sync::Arc::new(std::sync::Mutex::new(device_simulator::Device::new(&cli)));
        let mut connection = device_simulator::mqtt::Connection::new(&cli, device.clone())
            .expect("connection must be constructible");
        let (tx, mut steps) = mpsc::unbounded_channel();
        let (stop_tx, mut stop_rx) = tokio::sync::oneshot::channel();
        let (done_tx, done_rx) = tokio::sync::oneshot::channel();
        let kill = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
        let thread_kill = std::sync::Arc::clone(&kill);
        let ticked = std::sync::Arc::clone(&device);
        // A dedicated thread with its own current-thread runtime: rumqttc's
        // `EventLoop` is `Send` but not `Sync`, so the connection loop cannot
        // be `tokio::spawn`ed. Owning a thread also gives `kill()` a way to
        // drop the socket abruptly, which is what makes the will fire.
        let mut clock = AcceleratedClock::new(cli.time_scale);
        let thread = std::thread::spawn(move || {
            let runtime = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("test runtime");
            runtime.block_on(async move {
                loop {
                    if thread_kill.load(std::sync::atomic::Ordering::Relaxed) {
                        // Dropping the connection closes the socket with no
                        // DISCONNECT — exactly what a power cut looks like.
                        drop(connection);
                        return;
                    }
                    tokio::select! {
                        step = connection.step() => {
                            if let device_simulator::mqtt::Step::Disconnected { retry_in } = step {
                                // Tests must not wait out a full-jitter backoff.
                                tokio::time::sleep(retry_in.min(Duration::from_millis(200))).await;
                            }
                            if tx.send(step).is_err() {
                                return;
                            }
                        }
                        _ = &mut stop_rx => {
                            connection.shutdown().await;
                            let _ = done_tx.send(());
                            return;
                        }
                        // The run loop's ticker: converts elapsed real time into
                    // virtual time so sampling, the physical model, and the
                    // status heartbeat all advance, exactly as `runner::run`
                    // does in the binary.
                    () = tokio::time::sleep(TICK) => {
                        // The run loop's ticker: real elapsed time becomes
                        // virtual time at the configured scale, applied in the
                        // same bounded steps `runner::advance` uses, so a test
                        // at `--time-scale 600` exercises the same model
                        // behaviour as one at real time.
                        let elapsed = clock.take_elapsed_ms();
                        let publications = {
                            let mut device = device_simulator::mqtt::lock(&ticked);
                            AcceleratedClock::steps(elapsed)
                                .into_iter()
                                .flat_map(|step| device.tick(step))
                                .collect::<Vec<_>>()
                        };
                        connection.publish_all(&publications).await;
                    }
                    }
                }
            });
        });
        // Wait for the first ConnAck so a test never races the connection.
        let connected = tokio::time::timeout(RECEIVE_TIMEOUT, async {
            while let Some(step) = steps.recv().await {
                if step == device_simulator::mqtt::Step::Connected {
                    return true;
                }
            }
            false
        })
        .await
        .unwrap_or(false);
        assert!(connected, "the simulated device did not connect");
        Self {
            device,
            steps,
            kill,
            thread: Some(thread),
            shutdown: Some(stop_tx),
            finished: Some(done_rx),
        }
    }

    /// The device core, for asserting on internal state.
    pub fn core(&self) -> std::sync::MutexGuard<'_, device_simulator::Device> {
        self.device
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
    }

    /// Waits for a step satisfying a predicate.
    pub async fn next_step(
        &mut self,
        timeout: Duration,
        mut matches: impl FnMut(&device_simulator::mqtt::Step) -> bool,
    ) -> Option<device_simulator::mqtt::Step> {
        let deadline = tokio::time::Instant::now() + timeout;
        loop {
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() {
                return None;
            }
            match tokio::time::timeout(remaining, self.steps.recv()).await {
                Ok(Some(step)) if matches(&step) => return Some(step),
                Ok(Some(_)) => {}
                Ok(None) | Err(_) => return None,
            }
        }
    }

    /// Waits until the device has received a message on each of the given
    /// topics, in any order.
    pub async fn observe_inbound(&mut self, topics: &[String], timeout: Duration) -> Vec<String> {
        let mut outstanding: Vec<String> = topics.to_vec();
        let mut seen = Vec::new();
        while !outstanding.is_empty() {
            let Some(device_simulator::mqtt::Step::Inbound { topic }) = self
                .next_step(timeout, |s| {
                    matches!(s, device_simulator::mqtt::Step::Inbound { .. })
                })
                .await
            else {
                break;
            };
            if let Some(i) = outstanding.iter().position(|t| *t == topic) {
                outstanding.remove(i);
                seen.push(topic);
            }
        }
        seen
    }

    /// Stops the device cleanly, publishing `offline` with `reason: shutdown`.
    pub async fn stop_cleanly(mut self) {
        if let Some(stop) = self.shutdown.take() {
            let _ = stop.send(());
        }
        if let Some(done) = self.finished.take() {
            let _ = tokio::time::timeout(RECEIVE_TIMEOUT, done).await;
        }
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }

    /// Kills the device the way a power cut does: the socket closes with no
    /// DISCONNECT, so the broker publishes the will.
    pub fn kill(mut self) {
        self.kill.store(true, std::sync::atomic::Ordering::Relaxed);
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

impl Drop for SimulatedDevice {
    fn drop(&mut self) {
        self.kill.store(true, std::sync::atomic::Ordering::Relaxed);
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

/// Forces the device's connection closed the way the broker does when a second
/// client claims the same client id.
///
/// Connects once, waits for the acknowledgement, and disconnects — deliberately
/// *not* an auto-reconnecting client, which would fight the device for the id
/// and leave the test racing a ping-pong of evictions.
pub async fn evict(broker: &TestBroker, device_id: &str) {
    let mut options = MqttOptions::new(device_id, broker.host.clone(), broker.port);
    options.set_credentials(device_id, broker.device_password(device_id));
    options.set_clean_session(true);
    let (client, mut eventloop) = AsyncClient::new(options, 8);
    let connected = tokio::time::timeout(RECEIVE_TIMEOUT, async {
        loop {
            match eventloop.poll().await {
                Ok(Event::Incoming(Packet::ConnAck(_))) => return true,
                Ok(_) => {}
                Err(_) => return false,
            }
        }
    })
    .await
    .unwrap_or(false);
    assert!(connected, "the evicting client could not connect");
    let _ = client.disconnect().await;
    let _ = tokio::time::timeout(Duration::from_secs(2), eventloop.poll()).await;
    drop(eventloop);
}

/// Waits for a condition on the device core, polling briefly.
pub async fn eventually(timeout: Duration, mut condition: impl FnMut() -> bool) -> bool {
    let deadline = tokio::time::Instant::now() + timeout;
    while tokio::time::Instant::now() < deadline {
        if condition() {
            return true;
        }
        tokio::time::sleep(Duration::from_millis(25)).await;
    }
    condition()
}

/// A scratch path for a simulated device's persistent state.
pub fn scratch_state_file() -> std::path::PathBuf {
    static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let mut path = std::env::temp_dir();
    path.push("rhizo-device-simulator-integration");
    let _ = std::fs::create_dir_all(&path);
    path.push(format!(
        "{}-{}.state.json",
        std::process::id(),
        NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    for extension in ["json", "json.corrupt", "json.tmp"] {
        let _ = std::fs::remove_file(path.with_extension(extension));
    }
    let _ = std::fs::remove_file(&path);
    path
}

/// Publishes one message, waiting for the QoS 1 acknowledgement.
pub async fn publish(client: &AsyncClient, topic: &str, payload: &str, retain: bool) {
    client
        .publish(topic, QoS::AtLeastOnce, retain, payload.as_bytes().to_vec())
        .await
        .expect("publish must be accepted by the client");
}

/// Clears every retained edge->device topic for a device.
///
/// Retained `config` and `policy` outlive the test that published them, and a
/// sibling test's sampling interval arriving as retained state is a failure
/// whose cause appears nowhere in the assertion that reports it. A test that
/// depends on a known configuration clears it first and says so.
pub async fn clear_device_retained(broker: &TestBroker, device_id: &str) {
    let id = rhizo_mqtt_contract::DeviceId::parse(device_id).expect("a valid device id");
    let cleaner = broker
        .edge_subscriber(
            "test-retained-cleaner",
            &format!("rhizo/v1/devices/{device_id}/#"),
        )
        .await;
    // Every edge->device topic, not only the two that are *allowed* to be
    // retained. A retained `time` left behind by a previous run — a real
    // possibility, since that is precisely the mistake the retention test
    // exists to catch — would otherwise poison the broker for every later run,
    // and clearing it by hand is not something a test suite should require.
    for topic in [
        // `status` too: a device republishes it on connect, and leaving the
        // previous test's retained status in place lets a stale message
        // satisfy a matcher meant for a fresh one.
        rhizo_mqtt_contract::Topic::Status(id.clone()),
        rhizo_mqtt_contract::Topic::Config(id.clone()),
        rhizo_mqtt_contract::Topic::Policy(id.clone()),
        rhizo_mqtt_contract::Topic::Time(id.clone()),
        rhizo_mqtt_contract::Topic::CommandWater(id.clone()),
        rhizo_mqtt_contract::Topic::CommandTare(id.clone()),
        rhizo_mqtt_contract::Topic::CommandCalibrate(id.clone()),
        rhizo_mqtt_contract::Topic::CommandResult(id.clone()),
        rhizo_mqtt_contract::Topic::Telemetry(id.clone()),
        rhizo_mqtt_contract::Topic::Actuator(id.clone()),
        rhizo_mqtt_contract::Topic::Events(id),
    ] {
        clear_retained(&cleaner.client(), &topic.as_string()).await;
    }
    // Let the broker apply the deletions before the device subscribes, or it
    // would still be delivered the message being removed.
    tokio::time::sleep(Duration::from_millis(250)).await;
}

/// Clears a retained topic so one test cannot leak state into the next.
///
/// An empty retained payload is how MQTT deletes retained state.
pub async fn clear_retained(client: &AsyncClient, topic: &str) {
    client
        .publish(topic, QoS::AtLeastOnce, true, Vec::new())
        .await
        .expect("retained clear must be accepted");
}
